<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'userId'        => '0edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'ahmadalim',
                'userFullName'  => 'Ahmad Halimawan',
                'userEmail'     => 'ahmadhalim@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '1.jpg',
            ],
            [
                'userId'        => '132937b3-af6e-4a76-8402-b83142295cbb',
                'userName'      => 'johnsmith',
                'userFullName'  => 'John Andreas Smith',
                'userEmail'     => 'johnsmith@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '1.jpg',
            ],
            [
                'userId'        => '38f0cdc9-7268-4b5b-aca9-b8adbefbbc70',
                'userName'      => 'robertbrown',
                'userFullName'  => 'Ahmad Robert Brown',
                'userEmail'     => 'robertbrown@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '1.jpg',
            ],
            [
                'userId'        => '222c20fa-5f71-4fe6-8400-a2f7294bc81e',
                'userName'      => 'rudiahmad',
                'userFullName'  => 'Rudi Ahmad Tabudi',
                'userEmail'     => 'rudiahmad@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '1.jpg',
            ],
            [
                'userId'        => '8cf4acff-66e6-4ef6-94c9-49c243cbd3c9',
                'userName'      => 'jonesahay',
                'userFullName'  => 'Jones Ahay Gunawan',
                'userEmail'     => 'jonesahay@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'ban',
                'userAvatar'    => '1.jpg',
            ],
            [
                'userId'        => '0a8c0a27-9664-4afe-bd9f-b5f08062aeeb',
                'userName'      => 'meo',
                'userFullName'  => 'meoning',
                'userEmail'     => 'meoning@gmail.com',
                'userPassword'  => '$2y$10$kMEY7Y6.V8knWE6tWpaO4ez4HjvU1Q5t41Km4zVnHfI3HwBxsocKq',
                'userStatus'    => 'active',
                'userAvatar'    => '5.jpg',
            ],
            [
                'userId'        => '3c85de5d-b7fc-4dd6-917e-ce9df3eee6a7',
                'userName'      => 'sastra',
                'userFullName'  => 'sastrawati',
                'userEmail'     => 'sastra@gmail.com',
                'userPassword'  => '$2y$10$WiTHYpCcbirXZJrWG2S/jORhb36EhPf1WC4U289d7St.T6iJWgNO6',
                'userStatus'    => 'active',
                'userAvatar'    => '5.jpg',
            ],
            [
                'userId'        => 'd043be64-dcf7-4ee6-a40d-731ad3056c0e',
                'userName'      => 'jhoni',
                'userFullName'  => 'jhoni peni',
                'userEmail'     => 'jhoni@gmail.com',
                'userPassword'  => '$2y$10$L2FW3c8eGBssuIrL1.q9Q..twgVfYY4sKv09.KkZuzmVIvmfnhm26',
                'userStatus'    => 'active',
                'userAvatar'    => '8.jpg',
            ],
            [
                'userId'        => '731b7a70-ab78-403b-89bd-431f71924492',
                'userName'      => 'jumawa',
                'userFullName'  => 'jumawa',
                'userEmail'     => 'jumawa@gmail.com',
                'userPassword'  => '$2y$10$o.Wfv1RuJUXemeB9hLXpE.yqDpMS7FrNDtv0HarUPIp8yR9sicF..',
                'userStatus'    => 'active',
                'userAvatar'    => '4.jpg',
            ],
            [
                'userId'        => 'cf234ed3-3a4a-4bea-be28-4aa8e25b12c0',
                'userName'      => 'sanny',
                'userFullName'  => 'sanny oni',
                'userEmail'     => 'sanny@gmail.com',
                'userPassword'  => '$2y$10$JgorKJSPMOFXEKgi/KJdjOcFNo//IJvjawTX0VGrGAwwZE/2TL4JS',
                'userStatus'    => 'active',
                'userAvatar'    => '5.jpg',
            ],
            [
                'userId'        => 'bc13acad-6bbb-4231-b06a-d06a57c3a0db',
                'userName'      => 'coocaa',
                'userFullName'  => 'aci acian',
                'userEmail'     => 'coocaa@gmail.com',
                'userPassword'  => '$2y$10$qbrn3jC5BtZc4tfani295.tGmfagLZbeFHmcEDPPKGbypePuCrMom',
                'userStatus'    => 'active',
                'userAvatar'    => '7.jpg',
            ],
            [
                'userId'        => '1edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'budiwijaya',
                'userFullName'  => 'Budi Wijaya',
                'userEmail'     => 'budiwijaya@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '2edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'cindyputri',
                'userFullName'  => 'Cindy Putri',
                'userEmail'     => 'cindyputri@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '3edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'davidwijaya',
                'userFullName'  => 'David Wijaya',
                'userEmail'     => 'davidwijaya@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '4edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'erikwijaya',
                'userFullName'  => 'Erik Wijaya',
                'userEmail'     => 'erikwijaya@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '5edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'fionawijaya',
                'userFullName'  => 'Fiona Wijaya',
                'userEmail'     => 'fionawijaya@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '6edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'gabrielwijaya',
                'userFullName'  => 'Gabriel Wijaya',
                'userEmail'     => 'gabrielwijaya@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '7edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'hendrawijaya',
                'userFullName'  => 'Hendra Wijaya',
                'userEmail'     => 'hendrawijaya@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '8edfc13d-6e74-4518-a6fd-abf2ace8e626',
                'userName'      => 'indrawijaya',
                'userFullName'  => 'Indra Wijaya',
                'userEmail'     => 'indrawijaya@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => rand(1, 8) . '.jpg',
            ],
            [
                'userId'        => '123e4567-e89b-12d3-a456-426655440000',
                'userName'      => 'budi',
                'userFullName'  => 'Budi Santoso',
                'userEmail'     => 'budisantoso@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '2.jpg'
            ],
              [
                'userId'        => '2468acef-d10c-11db-9fe0-0800200c9a66',
                'userName'      => 'cici',
                'userFullName'  => 'Cici Sulistyowati',
                'userEmail'     => 'cicisulis@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '3.jpg'
              ],
              [
                'userId'        => '36910def-e21d-11db-9fe1-0800200c9a66',
                'userName'      => 'dani',
                'userFullName'  => 'Dani Wibowo',
                'userEmail'     => 'daniwibowo@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '4.jpg'
              ],
              [
                'userId'        => '48a21234-e32e-11db-9fe2-0800200c9a66',
                'userName'      => 'endi',
                'userFullName'  => 'Endi Setiawan',
                'userEmail'     => 'endisetiawan@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '5.jpg'
              ],
              [
                'userId'        => '5ab32456-e43f-11db-9fe3-0800200c9a66',
                'userName'      => 'fauzi',
                'userFullName'  => 'Fauzi Hidayat',
                'userEmail'     => 'fauzihidayat@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '6.jpg'
              ],
              [
                'userId'        => '6cd43678-e550-11db-9fe4-0800200c9a66',
                'userName'      => 'fitri',
                'userFullName'  => 'Fitria Sari',
                'userEmail'     => 'fitrisari@gmail.com',
                'userPassword'  => '$2a$12$G3L734KFl92IrEpBuWkMzOH53fpC35axI3V8gWnXnK6JctzqWDDcO',
                'userStatus'    => 'active',
                'userAvatar'    => '7.jpg'
              ],
        ];

        $this->db->table('User')->insertBatch($data);
    }
}